# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Moustapha Saad
tagline:          'C++ Plumber, loves Graphics and Compilers'
description:      'C++ Plumber, loves Graphics and Compilers. <a href="https://twitter.com/MoustaphaSaad" target="_blank">@MoustaphaSaad</a>.'
url:              https://moustaphasaad.github.io
baseurl:          /

author:
  name:           'Moustapha Saad'
  url:            https://twitter.com/MoustaphaSaad

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/MoustaphaSaad/MoustaphaSaad.github.io
