# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Moustapha Saad
tagline:          'C++ Plumber, loves Graphics and Compilers'
description:      'A Software Engineer at <a href="http://jekyllrb.com" target="_blank">360Imaging</a> Working on C++/Graphics at work/day and on Compilers at home/night. <a href="https://twitter.com/MoustaphaSaad" target="_blank">@MoustaphaSaad</a>.'
url:              https://moustaphasaad.github.io
baseurl:          /

author:
  name:           'Moustapha Saad'
  url:            https://twitter.com/MoustaphaSaad

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/MoustaphaSaad/MoustaphaSaad.github.io
